markdown: kramdown
baseurl: ""
title: DigiPres.org
subtitle: "Digital preservation community portal"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "communities"
    values:
      layout: "simple_page"
  - scope:
      path: "communities/local/*/*"
    values:
      layout: "local_group_page"
  - scope:
      path: "workflows"
    values:
      layout: "simple_page"

exclude:
  - _sources

include:
  - _data
  - _redirects

plugins:
  - jekyll-redirect-from
