markdown: kramdown
baseurl: ""

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude: ["_sources"]

plugins:
  - jekyll-redirect-from
