registries:
 - regId: fdd
   name: LoC FDD
 - regId: ffw
   name: FFW
 - regId: pronom
   name: PRONOM
 - regId: tika
   name: Tika
 - regId: trid
   name: TRiD
 - regId: githublinguist
   name: Github Linguist
 - regId: wikidata
   name: WikiData
